# This is CI/CD version 0.6.0
#
# Changelog
#
# v0.4.0 - 07.09.2024 (by eXory2024)
# Add environment variable "ANIO_CICD" for scripts to detect CI.
# "ANIO_CICD" contains the current CI/CD version.
#
# v0.5.0 - 21.09.2024 (by eXory2024)
# Use "npm ci" (require package-lock.json) instead of "npm i"
#
# v0.6.0 - 24.09.2024 (by eXory2024)
# Add manual "experimental" releases.
#

name: CI/CD Experimental release

on:
  workflow_dispatch:

jobs:
  # Run tests
  test:
    name: Run Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.x]
    env:
      ANIO_CICD: "v0.6.0"
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: "Install node modules (if present)"
        run: bash -c 'if [ -f package.json ]; then npm ci ; fi'

      - name: "Run .cicd/test.sh script (if present)"
        run: bash -c 'if [ -f ./.cicd/test.sh ]; then ./.cicd/test.sh ; fi'

  # Publish
  publish:
    name: Deployment
    runs-on: ubuntu-latest
    needs: test
    permissions:
      id-token: write
    env:
      ANIO_CICD: "v0.6.0"
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21.x
          registry-url: "https://registry.npmjs.org"

      - name: "Install node modules (if present)"
        run: bash -c 'if [ -f package.json ]; then npm ci ; fi'

      - name: Setup environment variables
        run: |
          echo "GIT_COMMIT_HASH_START=$(printf "${{ github.sha }}" | cut -c -8)" >> $GITHUB_ENV
          echo "GIT_COMMIT_HASH_END=$(printf "${{ github.sha }}" | rev | cut -c -8 | rev)" >> $GITHUB_ENV

      - name: "Run .cicd/deploy.sh script"
        run: ./.cicd/deploy.sh
        env:
          RELEASE_VERSION: "v0.0.0-experimental-${{ env.GIT_COMMIT_HASH_START }}-${{ env.GIT_COMMIT_HASH_END }}"

          NODE_AUTH_TOKEN: ${{ secrets.ANIO_NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.ANIO_NPM_TOKEN }}

          ANIO_SH_DEPLOY_URL: ${{ secrets.ANIO_SH_DEPLOY_URL }}
          ANIO_SH_DEPLOY_KEY: ${{ secrets.ANIO_SH_DEPLOY_KEY }}
